import { AIChatModelCard } from '@/types/aiModel';

const markaiChatModels: AIChatModelCard[] = [
  {
    contextWindowTokens: 128_000,
    description: 'DeepSeek-V3.1 是 DeepSeek 最新的大型语言模型，具有强大的推理和代码生成能力',
    displayName: 'DeepSeek-V3.1',
    enabled: true,
    id: 'deepseek-ai/DeepSeek-V3.1',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description: 'GPT OSS 120B 是一个开源的大型语言模型，提供强大的对话和文本生成能力',
    displayName: 'GPT OSS 120B',
    enabled: true,
    id: 'openai/gpt-oss-120b',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description: 'GLM-4.5 是智谱AI开发的多模态大型语言模型，支持文本理解和生成',
    displayName: 'GLM-4.5',
    enabled: true,
    id: 'zai-org/GLM-4.5',
    type: 'chat',
  },
  {
    contextWindowTokens: 200_000,
    description:
      'Claude Sonnet 4.5 是 Anthropic 的旗舰推理与编码模型，擅长复杂代理与计算机使用，支持长上下文与原生工具调用，适合大代码库与长文档分析。',
    displayName: 'claude-sonnet-4.5',
    enabled: true,
    id: 'claude-sonnet-4.5',
    type: 'chat',
  },
  {
    contextWindowTokens: 200_000,
    description:
      'Claude Sonnet 4.5（2025-09-29 版本）在长对话场景下的稳定性和上下文管理进一步增强，适合复杂工作流与代理式应用。',
    displayName: 'claude-sonnet-4-5-20250929',
    enabled: true,
    id: 'claude-sonnet-4-5-20250929',
    type: 'chat',
  },
  {
    contextWindowTokens: 134_000,
    description:
      'GPT-4o（2024-11-20）是 OpenAI 的多模态模型版本，强化了视觉理解、指令遵循与多语言能力，支持函数调用与文件处理，适合通用对话与分析。',
    displayName: 'gpt-4o-2024-11-20',
    enabled: true,
    id: 'gpt-4o-2024-11-20',
    type: 'chat',
  },
  {
    contextWindowTokens: 1_000_000,
    description:
      'GPT-4.1 提供最高 1,000,000 上下文窗口，长上下文检索与编码能力显著提升，工具使用更稳健，适合处理大型文档与代码库。',
    displayName: 'gpt-4.1',
    enabled: true,
    id: 'gpt-4.1',
    type: 'chat',
  },
  {
    contextWindowTokens: 1_000_000,
    description:
      'Gemini 2.5 Flash 主打低时延与长上下文的多模态理解，支持搜索、代码执行与 URL Context 等原生工具，适合快速响应的复杂任务。',
    displayName: 'gemini-2.5-flash',
    enabled: true,
    id: 'gemini-2.5-flash',
    type: 'chat',
  },
  {
    contextWindowTokens: 1_000_000,
    description:
      'MiniMax M2 注重可控推理与工具使用能力，兼顾性能、价格与速度，适合企业级部署与多场景应用。',
    displayName: 'MiniMaxAI/MiniMax-M2',
    enabled: true,
    id: 'MiniMaxAI/MiniMax-M2',
    type: 'chat',
  },
  {
    contextWindowTokens: 256_000,
    description:
      'Doubao 1.5 Pro 256k 主打性价比与稳定性，支持大上下文与多模态文档/图像理解，中文与推理表现出色。',
    displayName: 'doubao-pro-256k',
    enabled: true,
    id: 'doubao-pro-256k',
    type: 'chat',
  },
  {
    contextWindowTokens: 134_000,
    description:
      'OpenAI o3 系列的禁显思维变体，隐藏链式思考输出，专注快速、稳健的推理结果，适合对可见思维有严格要求的场景。',
    displayName: 'gpt-o3-nothinking',
    enabled: true,
    id: 'gpt-o3-nothinking',
    type: 'chat',
  },
  {
    contextWindowTokens: 200_000,
    description:
      'Claude Opus 4.1 Thinking 是高阶推理版本，强调更长的思维预算与更强的工具协同，适合复杂 STEM、代码与多步骤任务。',
    displayName: 'claude-opus-4-1-20250805-thinking',
    enabled: true,
    id: 'claude-opus-4-1-20250805-thinking',
    type: 'chat',
  },
  {
    contextWindowTokens: 200_000,
    description:
      'Claude Haiku 4.5（2025-10-01）为低时延轻量模型，响应迅速，适合高并发与日常问答，同时保留较强的工具与多模态能力。',
    displayName: 'claude-haiku-4-5-20251001',
    enabled: true,
    id: 'claude-haiku-4-5-20251001',
    type: 'chat',
  },
  {
    contextWindowTokens: 200_000,
    description:
      'Claude Sonnet 4（2025-05-14）在长上下文管理与代码生成方面表现稳定，适合企业级工作流与复杂代理应用。',
    displayName: 'claude-sonnet-4-20250514',
    enabled: true,
    id: 'claude-sonnet-4-20250514',
    type: 'chat',
  },
  {
    contextWindowTokens: 200_000,
    description:
      'Claude 4 Sonnet 标准版在推理、工具调用与代码能力之间取得良好平衡，适合通用生产环境。',
    displayName: 'claude-4-sonnet',
    enabled: true,
    id: 'claude-4-sonnet',
    type: 'chat',
  },
  {
    contextWindowTokens: 200_000,
    description: 'Claude 4 Sonnet Thinking 强化思维链推理能力，适用于多工具协作与复杂问题求解。',
    displayName: 'claude-4-sonnet-thinking',
    enabled: true,
    id: 'claude-4-sonnet-thinking',
    type: 'chat',
  },
  {
    contextWindowTokens: 200_000,
    description:
      'Claude 4 Opus Thinking 为顶级推理能力的旗舰版本，面向深度复杂场景与高可靠性要求。',
    displayName: 'claude-4-opus-thinking',
    enabled: true,
    id: 'claude-4-opus-thinking',
    type: 'chat',
  },
  {
    contextWindowTokens: 200_000,
    description:
      'Claude 3.5 Sonnet（2024-10-22）在编码与工具使用方面稳定，适合通用任务与生产环境。',
    displayName: 'claude-3-5-sonnet-20241022',
    enabled: true,
    id: 'claude-3-5-sonnet-20241022',
    type: 'chat',
  },
  {
    contextWindowTokens: 200_000,
    description: 'Claude 3.5 Haiku（2024-10-22）为轻量快模型，成本友好，适合日常问答与高并发流量。',
    displayName: 'claude-3-5-haiku-20241022',
    enabled: true,
    id: 'claude-3-5-haiku-20241022',
    type: 'chat',
  },
  {
    contextWindowTokens: 400_000,
    description:
      'GPT‑5 统一推理、多模态与工具使用，显著降低幻觉率，适合复杂多步骤工作流与企业生产。',
    displayName: 'gpt-5',
    enabled: true,
    id: 'gpt-5',
    type: 'chat',
  },
  {
    contextWindowTokens: 400_000,
    description:
      'GPT‑5（2025-08-07）正式版，提升长上下文与编码表现，支持更稳健的指令遵循与多模态处理。',
    displayName: 'gpt-5-2025-08-07',
    enabled: true,
    id: 'gpt-5-2025-08-07',
    type: 'chat',
  },
  {
    contextWindowTokens: 400_000,
    description: 'GPT‑5 Codex High 为高配编程变体，面向大代码库、复杂重构与多语言工程任务。',
    displayName: 'gpt-5-codex-high',
    enabled: true,
    id: 'gpt-5-codex-high',
    type: 'chat',
  },
  {
    contextWindowTokens: 400_000,
    description: 'GPT‑5 Codex Low 为经济型编程变体，在保持代码能力的同时降低时延与成本。',
    displayName: 'gpt-5-codex-low',
    enabled: true,
    id: 'gpt-5-codex-low',
    type: 'chat',
  },
  {
    contextWindowTokens: 400_000,
    description: 'GPT‑5 Nano 强调极低时延与成本，适合实时产品与边缘设备场景。',
    displayName: 'gpt-5-nano',
    enabled: true,
    id: 'gpt-5-nano',
    type: 'chat',
  },
  {
    contextWindowTokens: 400_000,
    description: 'GPT‑5 Chat 面向对话优化，指令遵循与多轮上下文处理更稳健。',
    displayName: 'gpt-5-chat',
    enabled: true,
    id: 'gpt-5-chat',
    type: 'chat',
  },
  {
    contextWindowTokens: 400_000,
    description: 'GPT‑5 Chat 最新通道，持续获得对话与工具能力更新，适合生产环境。',
    displayName: 'gpt-5-chat-latest',
    enabled: true,
    id: 'gpt-5-chat-latest',
    type: 'chat',
  },
  {
    contextWindowTokens: 400_000,
    description: 'GPT‑5 Mini（2025-08-07）小型化变体，保持稳定推理与工具使用，成本更优。',
    displayName: 'gpt-5-mini-2025-08-07',
    enabled: true,
    id: 'gpt-5-mini-2025-08-07',
    type: 'chat',
  },
  {
    contextWindowTokens: 400_000,
    description: 'GPT‑5 Mini 标准通道，适合中等复杂度任务与高并发请求。',
    displayName: 'gpt-5-mini',
    enabled: true,
    id: 'gpt-5-mini',
    type: 'chat',
  },
  {
    contextWindowTokens: 400_000,
    description: 'GPT‑5 Fast 注重低时延响应，适合实时产品与交互场景。',
    displayName: 'gpt-5-fast',
    enabled: true,
    id: 'gpt-5-fast',
    type: 'chat',
  },
  {
    contextWindowTokens: 400_000,
    description: 'GPT‑5 Medium 在速度与能力之间取得良好平衡，适合通用生产负载。',
    displayName: 'gpt-5-medium',
    enabled: true,
    id: 'gpt-5-medium',
    type: 'chat',
  },
  {
    contextWindowTokens: 400_000,
    description: 'GPT‑5 High 提供更高能力预算，适合复杂任务、长上下文与多工具工作流。',
    displayName: 'gpt-5-high',
    enabled: true,
    id: 'gpt-5-high',
    type: 'chat',
  },
  {
    contextWindowTokens: 400_000,
    description: 'GPT‑5 Nothinking 禁显思维输出，专注给出稳健结果，适合合规与审计场景。',
    displayName: 'gpt-5-nothinking',
    enabled: true,
    id: 'gpt-5-nothinking',
    type: 'chat',
  },
  {
    contextWindowTokens: 400_000,
    description: 'GPT‑5 Mini Nothinking 禁显思维输出的小型化版本，适合高并发与成本敏感场景。',
    displayName: 'gpt-5-Mini-nothinking',
    enabled: true,
    id: 'gpt-5-Mini-nothinking',
    type: 'chat',
  },
  {
    contextWindowTokens: 400_000,
    description: 'GPT‑5 Nano Nothinking 极低时延禁显思维版本，适合边缘与实时系统。',
    displayName: 'gpt-5-Nano-nothinking',
    enabled: true,
    id: 'gpt-5-Nano-nothinking',
    type: 'chat',
  },
  {
    contextWindowTokens: 134_000,
    description: 'GPT‑4.5 作为过渡版本提升推理与稳定性，为 GPT‑5 的统一能力奠定基础。',
    displayName: 'gpt-4.5',
    enabled: true,
    id: 'gpt-4.5',
    type: 'chat',
  },
  {
    contextWindowTokens: 134_000,
    description: 'GPT‑4 Turbo 在结构化输出与多语言能力上表现稳定，适合生产环境 JSON/函数调用。',
    displayName: 'gpt-4-turbo',
    enabled: true,
    id: 'gpt-4-turbo',
    type: 'chat',
  },
  {
    contextWindowTokens: 134_000,
    description: 'GPT‑4o 为 OpenAI 多模态主力模型，视觉理解、指令遵循与多语言能力全面增强。',
    displayName: 'gpt-4o',
    enabled: true,
    id: 'gpt-4o',
    type: 'chat',
  },
  {
    contextWindowTokens: 134_000,
    description: 'GPT‑4o Mini 的禁显思维变体，适合低成本与高并发的通用场景。',
    displayName: 'gpt-4o-mini-nothinking',
    enabled: true,
    id: 'gpt-4o-mini-nothinking',
    type: 'chat',
  },
  {
    contextWindowTokens: 134_000,
    description: 'GPT‑4o Mini 小型化多模态版本，成本友好，适合集成到应用与批量任务。',
    displayName: 'openai/gpt-4o-mini',
    enabled: true,
    id: 'openai/gpt-4o-mini',
    type: 'chat',
  },
  {
    contextWindowTokens: 1_000_000,
    description: 'GPT‑4.1 Nano 为极小型长上下文版本，面向超长文档与高吞吐应用的长上下文处理。',
    displayName: 'gpt-4.1-nano',
    enabled: true,
    id: 'gpt-4.1-nano',
    type: 'chat',
  },
  {
    contextWindowTokens: 1_000_000,
    description: 'GPT‑4.1 Nano（2025-04-14）版本，提供 1M 上下文与更稳健的长上下文检索能力。',
    displayName: 'gpt-4.1-nano-2025-04-14',
    enabled: true,
    id: 'gpt-4.1-nano-2025-04-14',
    type: 'chat',
  },
  {
    contextWindowTokens: 1_000_000,
    description: 'GPT‑4o Mini 的增强长上下文通道，适合处理大型文档与代码仓库。',
    displayName: 'gpt-4o-mini',
    enabled: true,
    id: 'gpt-4o-mini',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description:
      'DeepSeek-V3.2-Exp 为强化实验通道，提升函数调用与长上下文稳定性，适合复杂业务集成。',
    displayName: 'deepseek-ai/DeepSeek-V3.2-Exp',
    enabled: true,
    id: 'deepseek-ai/DeepSeek-V3.2-Exp',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description: 'DeepSeek-V3.2 是 V3 系列的增强版本，兼顾性能与成本，适合通用对话与分析。',
    displayName: 'deepseek-v3.2',
    enabled: true,
    id: 'deepseek-v3.2',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description: 'DeepSeek-V3.1 Terminus 专注长会话稳定性与复杂工作流，适合企业级生产环境。',
    displayName: 'deepseek-ai/DeepSeek-V3.1-Terminus',
    enabled: true,
    id: 'deepseek-ai/DeepSeek-V3.1-Terminus',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description: 'DeepSeek-V3.1 标准通道，推理与代码能力强，适合通用场景。',
    displayName: 'deepseek-v3.1',
    enabled: true,
    id: 'deepseek-v3.1',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description: 'DeepSeek-V3 通用模型，提供稳定的函数调用与多轮对话能力。',
    displayName: 'deepseek-v3',
    enabled: true,
    id: 'deepseek-v3',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description: 'DeepSeek-R1 推理模型，强化复杂推理任务与工具协同，适合数学、代码与搜索场景。',
    displayName: 'deepseek-r1',
    enabled: true,
    id: 'deepseek-r1',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description: 'DeepSeek-R1-Distill-Llama-70B 为蒸馏版本，保留强推理能力同时降低推理开销。',
    displayName: 'deepseek-ai/DeepSeek-R1-Distill-Llama-70B',
    enabled: true,
    id: 'deepseek-ai/DeepSeek-R1-Distill-Llama-70B',
    type: 'chat',
  },
  {
    contextWindowTokens: 200_000,
    description: 'GLM‑4.6 为业界领先的中文与多模态模型之一，推理与编码能力全面提升。',
    displayName: 'glm-4.6',
    enabled: true,
    id: 'glm-4.6',
    type: 'chat',
  },
  {
    contextWindowTokens: 200_000,
    description: 'GLM‑4.6（智谱）在推理与工具协作方面提升显著，适合企业级应用。',
    displayName: 'zai-org/GLM-4.6:zai-org',
    enabled: true,
    id: 'zai-org/GLM-4.6:zai-org',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description: 'GLM‑4.5（智谱）多模态能力稳定，中文场景表现优异。',
    displayName: 'zai-org/GLM-4.5:zai-org',
    enabled: true,
    id: 'zai-org/GLM-4.5:zai-org',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description: 'GLM‑4.5V 聚焦视觉理解，多模态分析能力更强，适合图文混合任务。',
    displayName: 'zai-org/GLM-4.5V:zai-org',
    enabled: true,
    id: 'zai-org/GLM-4.5V:zai-org',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description: 'GLM‑4.5 Air 为轻量化版本，响应更快、成本更低，适合高并发场景。',
    displayName: 'zai-org/GLM-4.5-Air:zai-org',
    enabled: true,
    id: 'zai-org/GLM-4.5-Air:zai-org',
    type: 'chat',
  },
  {
    description:
      'DeepSeek-OCR 专注文档与版面视觉文本解析，采用上下文光学压缩，极大降低视觉 token，适合高分辨率文档的高效 OCR。',
    displayName: 'deepseek-ai/DeepSeek-OCR',
    enabled: true,
    id: 'deepseek-ai/DeepSeek-OCR',
    type: 'chat',
  },
  {
    contextWindowTokens: 256_000,
    description: 'Kimi-K2 Thinking 强化思维链与工具协同，适合复杂任务与长文档分析。',
    displayName: 'moonshotai/Kimi-K2-Thinking',
    enabled: true,
    id: 'moonshotai/Kimi-K2-Thinking',
    type: 'chat',
  },
  {
    contextWindowTokens: 256_000,
    description: 'Kimi-K2 Instruct（0905）指令优化版本，响应更稳健，适合生产环境。',
    displayName: 'kimi-k2-0905',
    enabled: true,
    id: 'kimi-k2-0905',
    type: 'chat',
  },
  {
    contextWindowTokens: 256_000,
    description: 'Kimi-K2 标准通道，兼顾推理、代码与工具使用能力。',
    displayName: 'kimi-k2',
    enabled: true,
    id: 'kimi-k2',
    type: 'chat',
  },
  {
    contextWindowTokens: 256_000,
    description: 'Qwen3-Max 为通用旗舰版本，长上下文与指令遵循更强，适合复杂业务。',
    displayName: 'qwen3-max',
    enabled: true,
    id: 'qwen3-max',
    type: 'chat',
  },
  {
    contextWindowTokens: 256_000,
    description: 'Qwen3-Max Preview 预览通道，提供更快的更新节奏与新能力试用。',
    displayName: 'qwen3-max-preview',
    enabled: true,
    id: 'qwen3-max-preview',
    type: 'chat',
  },
  {
    contextWindowTokens: 256_000,
    description: 'Qwen3-VL-Plus 多模态旗舰，文档与图像理解更强，适合复杂视觉任务。',
    displayName: 'qwen3-vl-plus',
    enabled: true,
    id: 'qwen3-vl-plus',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description: 'Qwen3-Next 80B Instruct 面向指令任务的大参数版本，推理与编码表现稳定。',
    displayName: 'Qwen/Qwen3-Next-80B-A3B-Instruct',
    enabled: true,
    id: 'Qwen/Qwen3-Next-80B-A3B-Instruct',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description: 'Qwen3-Next 80B Thinking 强化推理过程，适合多步骤复杂问题与工具协作。',
    displayName: 'Qwen/Qwen3-Next-80B-A3B-Thinking',
    enabled: true,
    id: 'Qwen/Qwen3-Next-80B-A3B-Thinking',
    type: 'chat',
  },
  {
    contextWindowTokens: 256_000,
    description: 'Qwen3-Coder-Plus 面向代码生成与重构的通道，适合工程场景。',
    displayName: 'qwen3-coder-plus',
    enabled: true,
    id: 'qwen3-coder-plus',
    type: 'chat',
  },
  {
    contextWindowTokens: 256_000,
    description: 'Qwen3-Coder 标准编程通道，平衡性能与成本。',
    displayName: 'qwen3-coder',
    enabled: true,
    id: 'qwen3-coder',
    type: 'chat',
  },
  {
    contextWindowTokens: 262_000,
    description: 'Qwen3 Coder 480B A35B Instruct 超大规模代码模型，适合复杂重构与跨语言工程。',
    displayName: 'Qwen/Qwen3-Coder-480B-A35B-Instruct',
    enabled: true,
    id: 'Qwen/Qwen3-Coder-480B-A35B-Instruct',
    type: 'chat',
  },
  {
    contextWindowTokens: 256_000,
    description: 'Qwen3-235B A22B Thinking（2507）大参数推理版本，适合复杂任务与长上下文。',
    displayName: 'qwen3-235b-a22b-thinking-2507',
    enabled: true,
    id: 'qwen3-235b-a22b-thinking-2507',
    type: 'chat',
  },
  {
    contextWindowTokens: 256_000,
    description: 'Qwen3-235B A22B Instruct 大参数指令版本，适合企业级生产工作流。',
    displayName: 'qwen3-235b-a22b-instruct',
    enabled: true,
    id: 'qwen3-235b-a22b-instruct',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description: 'Qwen3-235B A22B Thinking（2507）增强推理过程，面向复杂多步骤问题求解。',
    displayName: 'Qwen/Qwen3-235B-A22B-Thinking-2507',
    enabled: true,
    id: 'Qwen/Qwen3-235B-A22B-Thinking-2507',
    type: 'chat',
  },
  {
    contextWindowTokens: 128_000,
    description: 'Qwen3-VL-235B A22B Thinking 多模态大参数版本，视觉理解与推理能力更强。',
    displayName: 'Qwen/Qwen3-VL-235B-A22B-Thinking',
    enabled: true,
    id: 'Qwen/Qwen3-VL-235B-A22B-Thinking',
    type: 'chat',
  },
];

export const allModels = [...markaiChatModels];

export default allModels;
